name: CD - Continous Deployment 

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build 
      env: 
        DOCKER_HUB: "Docker username "
        DOCKER_KEY: "Docker Repo password "
      run: |
        ls -l
        echo "Logging into Docker"
        echo "Logged in success"
        echo "Running the build"
        docker build -t ultrasoft/angular .
        echo 'pushing image..'
        echo "docker image build and pushed"
   
